# Generated by Django 5.0.7 on 2024-07-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="post.movie",
            ),
        ),
    ]
