# Generated by Django 5.0.7 on 2024-07-12 23:13

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_comment_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=post.models.image_upload_path
            ),
        ),
    ]
