# Generated by Django 5.0.7 on 2024-07-16 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_comment_writer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie",
            new_name="Post",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="movie",
            new_name="post",
        ),
    ]
