# Generated by Django 5.0.7 on 2024-07-16 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_post_writer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
